name: Conventional Commits

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
