services:
  db:
    image: postgres:18
    restart: always
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080