@startuml Order Ready Flow
hide footbox

actor Staff

boundary "OrderActionsComponent" as Component
control "http/order.ts" as Http
control "application/mark-order-ready.ts" as UseCase

Staff ->> Component: click mark ready

Component ->> Http: PATCH /v1/orders/:id/ready
activate Http

Http -> Http: markOrderReadyDto.safeParseAsync({id})

alt validation fails
    Http -->> Component: 400 {"message": "validation error"}
else validation succeeds
    Http ->> UseCase: markOrderReadyUseCase({id})
    activate UseCase

    create entity "repo/order-repo.ts" as OrderRepo
    database "Postgres DB" as DB
    UseCase ->> OrderRepo: <<create>>
    activate OrderRepo

    UseCase ->> OrderRepo: findById(id)

    OrderRepo ->> DB: SELECT * FROM order WHERE id
    activate DB
    DB -->> OrderRepo: order
    deactivate DB

    alt order not found
        OrderRepo -->> UseCase: null
        UseCase -->> Http: Err(OrderNotFound)
        Http -->> Component: 404 {"message": "order not found"}
    else order found
        OrderRepo -->> UseCase: order

        alt order already ready
            UseCase -->> Http: Err(OrderAlreadyMark)
            Http -->> Component: 400 {"message": "order already ready"}
        else order can be marked
            UseCase ->> OrderRepo: orderReady(id)

            OrderRepo ->> DB: UPDATE order SET status = ready
            DB -->> OrderRepo: updatedOrder
            deactivate OrderRepo

            UseCase -->> Http: Ok(updatedOrder)
            Http -->> Component: 200 {order}
        end
    end
end

deactivate Http

alt success
    Component -->> Staff: show success notification
else error
    Component -->> Staff: show error message
end

@enduml
