@startuml Discount Update Flow
hide footbox

actor Admin

boundary "DiscountFormComponent" as Component
control "http/discount.ts" as Http
control "application/update-discount.ts" as UseCase

Admin ->> Component: submit discount updates

Component ->> Http: PATCH /v1/discounts/{id}
activate Http

Http -> Http: UpdateDiscountDto.safeParseAsync(body)

alt validation fails
    Http -->> Component: 400 {"message": "validation error"}
else validation succeeds
    Http ->> UseCase: updateDiscountUseCase(id, data)
    activate UseCase

    create entity "repo/discount-repo.ts" as DiscountRepo
    database "Postgres DB" as DB
    UseCase ->> DiscountRepo: <<create>>
    activate DiscountRepo

    UseCase ->> DiscountRepo: findDiscountById(id)

    DiscountRepo ->> DB: SELECT * FROM discount WHERE id
    activate DB
    DB -->> DiscountRepo: discount
    deactivate DB

    alt discount not found
        DiscountRepo -->> UseCase: null
        UseCase -->> Http: Err(DiscountNotFoundError)
        Http -->> Component: 404 {"message": "discount not found"}
    else discount found
        UseCase ->> DiscountRepo: updateDiscount(id, data)
        DiscountRepo ->> DB: UPDATE discount SET ... WHERE id
        DB -->> DiscountRepo: discount
        deactivate DiscountRepo

        UseCase -->> Http: Ok(discount)
        Http -->> Component: 200 {discount}
    end
end

deactivate Http

alt success
    Component -->> Admin: redirect to discount list
else error
    Component -->> Admin: show error message
end

@enduml

