@startuml User Get Profile Flow
hide footbox

actor User

boundary "ProfilePageComponent" as Component
control "http/user.ts" as Http
control "application/get-actor.ts" as UseCase

User ->> Component: view profile

Component ->> Http: GET /v1/users/@me
activate Http

Http -> UseCase: getActorUseCase(userId)
activate UseCase

create entity "repo/user-repo.ts" as UserRepo
database "Postgres DB" as DB
UseCase ->> UserRepo: <<create>>
activate UserRepo

UseCase ->> UserRepo: findByIdWithRole(userId)

UserRepo ->> DB: SELECT * FROM user LEFT JOIN user_roles WHERE id
activate DB
DB -->> UserRepo: userWithRole
deactivate DB

alt user not found
    UserRepo -->> UseCase: null
    UseCase -->> Http: Err(ActorNotFoundError)
    Http -->> Component: 404 {"message": "user not found"}
else user found
    UserRepo -->> UseCase: userWithRole
    UseCase -->> Http: Ok({id, email, phone, firstName, lastName, role})
    Http -->> Component: 200 {actor}
end
deactivate UserRepo

deactivate Http

alt success
    Component -->> User: render profile
else error
    Component -->> User: show error
end

@enduml
